import {
  Award,
  Bot,
  BookOpen,
  Briefcase,
  Bug,
  Cloud,
  CloudCog,
  Code2,
  Download,
  FileText,
  FlaskConical,
  GraduationCap,
  Lock,
  Mail,
  MapPin,
  MapPinned,
  Microscope,
  Network,
  Phone,
  Scale,
  Send,
  Shield,
  ShieldCheck,
  Smartphone,
  BadgeCheck,
  Sparkles,
  User,
  Workflow,
  type LucideIcon,
} from "lucide-react";

/**
 * Semantic icon names ported from the Stitch mockup's Material Symbols
 * (e.g. `location_on`, `bug_report`) to lucide-react equivalents. Keeping
 * this mapping in one file isolates the icon-set choice from content data.
 */
export const iconMap = {
  verified: BadgeCheck,
  location: MapPin,
  phone: Phone,
  mail: Mail,
  school: GraduationCap,
  send: Send,
  download: Download,
  balance: Scale,
  hub: Network,
  science: FlaskConical,
  bug: Bug,
  shield: Shield,
  bot: Bot,
  workflow: Workflow,
  briefcase: Briefcase,
  book: BookOpen,
  person: User,
  file: FileText,
  code: Code2,
  shieldCheck: ShieldCheck,
  cloudDone: CloudCog,
  microscope: Microscope,
  award: Award,
  lock: Lock,
  cloud: Cloud,
  brain: Sparkles,
  smartphone: Smartphone,
  pin: MapPinned,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
